services: docker
language: minimal
install: skip
script:
  - git clone -b distribute-axi-uart --recurse-submodules https://github.com/1138-4EB/vunit /tmp/vunit
  - git clone https://github.com/VUnit/vc_axi
  - docker run --rm -tv /tmp/vunit:/tmp/vunit -e CI=$CI -e PYTHONPATH=/tmp/vunit -v $(pwd):/src -w /src vunit/dev:llvm tox -e py37-examples-ghdl

